const data = {
  topics:[['PUBLIC LIFE','How a local ordinance becomes real','Follow an idea from a neighborhood conversation to a signed ordinance.',62],['DEMOCRACY','Beyond election day','Four practical ways people shape decisions between elections.',20],['CAMPUS','Making a proposal people can use','Turn a complaint into a clear, research-backed proposal.',0]],
  posts:[['CAMPUS PULSE · 2H','Should the library stay open later during finals?','A student proposal suggests a two-week pilot for extended study hours. What evidence would help make the case?','18 reflections'],['LOCAL LIFE · 5H','Safer walking routes after evening classes','Students are mapping poorly lit routes and collecting anonymous safety observations.','31 contributors'],['OPEN QUESTION · YESTERDAY','What does meaningful student consultation look like?','Share an example of when feedback changed a decision—or when it should have.','24 reflections']],
  projects:[['ACTIVE','Study After Dark','A student-led pilot for safe, accessible evening study spaces.','8 people · Next check-in Friday',72],['FORMING','Street-to-School Map','Map barriers on the route between campus and public transport.','5 people · Looking for volunteers',35],['COMPLETED','First-Time Voter Kit','Plain-language materials for students registering to vote.','42 students reached',100]]
};
const view = document.querySelector('#view');
const modal = document.querySelector('#modal');
const escape = text => text.replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const openModal = (title, body) => { modal.innerHTML=`<h2>${escape(title)}</h2><p>${escape(body)}</p><button class="button" onclick="document.querySelector('#modal').close()">Got it</button>`; modal.showModal(); };
window.openModal = openModal;
const templates = {
  today:()=>`<section class="hero"><p class="eyebrow">SATURDAY · JULY 19</p><h1 class="display">Make your corner<br>of campus count.</h1><p class="lede">Civic Circle gives ideas a path—from the first question to visible community action.</p></section><section class="daily-card"><p class="eyebrow">YOUR NEXT STEP · 7 MINUTES</p><h2>Help shape the case for safer routes home.</h2><p>Read three student observations, then add yours to the Street-to-School Map.</p><button class="button" data-view="projects">See the project →</button></section><div class="section-head"><div><p class="eyebrow">START HERE</p><h2>A small civic practice</h2></div></div><section class="action-row"><button class="action" data-view="explore"><span>⌁</span><b>Learn</b><small>One idea, clearly explained</small></button><button class="action" data-view="pulse"><span>◌</span><b>Reflect</b><small>Add evidence to a question</small></button><button class="action" data-view="projects"><span>▧</span><b>Contribute</b><small>Move a project forward</small></button></section><div class="section-head"><div><p class="eyebrow">IN THE CIRCLE</p><h2>Worth your attention</h2></div><button class="text-button" data-view="pulse">View pulse</button></div><article class="story-card"><span class="story-number">01</span><div><h3>Library hours proposal</h3><p>18 students have reflected. The proposal is collecting evidence.</p></div><button data-view="pulse">→</button></article>`,
  explore:()=>`<section class="hero"><p class="eyebrow">EXPLORE</p><h1 class="display">Understand the systems around you.</h1><p class="lede">Short, practical civic stories made for the questions students actually ask.</p></section><section class="topic-grid">${data.topics.map((t,i)=>`<article class="topic"><span class="label">${t[0]}</span><h3>${t[1]}</h3><p>${t[2]}</p><div class="progress"><i style="width:${t[3]}%"></i></div><p>${t[3] ? `${t[3]}% explored` : 'New path'}</p><button class="text-button" onclick="openModal('${t[1]}','This learning path opens with an interactive, plain-language story and ends with a practical reflection.')">Open path →</button></article>`).join('')}</section>`,
  pulse:()=>`<section class="hero"><p class="eyebrow">CAMPUS PULSE</p><h1 class="display">Questions worth taking seriously.</h1><p class="lede">A moderated space for observations, proposals, and respectful disagreement.</p></section><button class="button" onclick="openModal('Start a question','A good civic question is specific, grounded in experience, and open to evidence.')">Start a question</button><section class="section-head"><div><p class="eyebrow">RECENT CONVERSATIONS</p><h2>Listen, then add something useful</h2></div></section><section>${data.posts.map(p=>`<article class="post"><span class="post-meta">${p[0]}</span><h3>${p[1]}</h3><p>${p[2]}</p><div class="post-footer"><span>♡ ${p[3]}</span><button class="text-button" onclick="openModal('Add a reflection','Thanks for contributing. In the full app, this would open a guided response that asks for your experience or evidence.')">Reflect →</button></div></article>`).join('')}</section>`,
  projects:()=>`<section class="hero"><p class="eyebrow">PROJECTS</p><h1 class="display">Move from concern to change.</h1><p class="lede">Work with people who care about the same thing. Every project makes its progress visible.</p></section><button class="button" onclick="openModal('Start a project','Begin with the problem, who it affects, and the smallest action your team can take this week.')">Start a project</button><section class="section-head"><div><p class="eyebrow">COMMUNITY WORK</p><h2>Projects in motion</h2></div></section><section class="project-grid">${data.projects.map(p=>`<article class="project"><span class="project-status">${p[0]}</span><h3>${p[1]}</h3><p>${p[2]}</p><p>${p[3]}</p><div class="progress"><i style="width:${p[4]}%"></i></div><p>${p[4]}% toward this cycle’s goal</p></article>`).join('')}</section>`,
  profile:()=>`<section class="hero"><p class="eyebrow">MY CIVIC PASSPORT</p><h1 class="display">A record of showing up.</h1><div class="profile-meta"><b>Lea Mendoza</b><span>2nd-year student · Joined Civic Circle 2026</span></div></section><section class="passport"><p class="eyebrow">YOUR PASSPORT</p><h2>6 moments of participation</h2><p>Not a score—just a growing record of learning, listening, and contributing.</p><div class="stamp-grid"><span class="stamp earned">LEARNED<br>THE BASICS</span><span class="stamp earned">JOINED<br>A DIALOGUE</span><span class="stamp earned">MAPPED<br>AN ISSUE</span><span class="stamp earned">PROJECT<br>CONTRIBUTOR</span><span class="stamp">HOSTED<br>A SESSION</span><span class="stamp">SHARED<br>AN OUTCOME</span></div></section><div class="section-head"><div><p class="eyebrow">YOUR NEXT MILESTONE</p><h2>Share an outcome</h2></div></div><article class="story-card"><span class="story-number">07</span><div><h3>Close the loop</h3><p>Post what changed—or what you learned—after a project activity.</p></div><button data-view="projects">→</button></article>`
};
function render(name){view.innerHTML=templates[name](); document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>render(button.dataset.view))); document.querySelectorAll('.nav-item').forEach(button=>button.classList.toggle('active',button.dataset.view===name)); window.scrollTo({top:0,behavior:'smooth'});}
document.querySelector('#theme-toggle').addEventListener('click',()=>document.body.classList.toggle('night'));
if('serviceWorker'in navigator) navigator.serviceWorker.register('./service-worker.js');
render('today');
